---
- name: Install essential dependencies
  become: true
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - build-essential
    - git
    - vim
    - xcb
    - libxcb-util0-dev
    - libxcb-ewmh-dev
    - libxcb-randr0-dev
    - libxcb-icccm4-dev
    - libxcb-keysyms1-dev
    - libxcb-xinerama0-dev
    - libasound2-dev
    - libxcb-xtest0-dev
    - libxcb-shape0-dev
    - net-tools

- name: Install Polybar dependencies
  become: true
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - cmake
    - cmake-data
    - pkg-config
    - python3-sphinx
    - libcairo2-dev
    - libxcb1-dev
    - libxcb-util0-dev
    - libxcb-randr0-dev
    - libxcb-composite0-dev
    - python3-xcbgen
    - xcb-proto
    - libxcb-image0-dev
    - libxcb-ewmh-dev
    - libxcb-icccm4-dev
    - libxcb-xkb-dev
    - libxcb-xrm-dev
    - libxcb-cursor-dev
    - libasound2-dev
    - libpulse-dev
    - libjsoncpp-dev
    - libmpdclient-dev
    - libuv1-dev
    - libnl-genl-3-dev
    - g++

- name: Install Picom dependencies
  become: true
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - meson
    - libxext-dev
    - libxcb1-dev
    - libxcb-damage0-dev
    - libxcb-xfixes0-dev
    - libxcb-shape0-dev
    - libxcb-render-util0-dev
    - libxcb-render0-dev
    - libxcb-composite0-dev
    - libxcb-image0-dev
    - libxcb-present-dev
    - libxcb-xinerama0-dev
    - libpixman-1-dev
    - libdbus-1-dev
    - libconfig-dev
    - libgl1-mesa-dev
    - libpcre2-dev
    - libevdev-dev
    - uthash-dev
    - libev-dev
    - libx11-xcb-dev
    - libxcb-glx0-dev
    - libpcre3
    - libpcre3-dev

- name: Install additional packages
  become: true
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - feh
    - scrot
    - scrub
    - zsh
    - rofi
    - xclip
    - bat
    - locate
    - neofetch
    - wmname
    - acpi
    - bspwm
    - sxhkd
    - imagemagick
    - ranger
    - kitty
